name: Update Feed and Car Detail

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Update cars.json
        run: python fetch_api_to_json.py

      - name: Generate car-detail HTML
        run: python generate_car_detail.py

      - name: Generate feed.xml
        run: python generate_feed.py

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "auto update cars and feed" || true
          git push