name: Update RSS Feed

on:
  schedule:
    - cron: '0 */3 * * *' # ทุก 3 ชั่วโมง
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests

      - name: Generate feed.xml
        run: python make_feed.py

      - name: Commit & Push feed.xml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feed.xml
          git commit -m "Update feed.xml [auto]" || echo "No changes to commit"
          git push
        env:
          # ให้สิทธิ์ push กลับไปยัง repo เดิม
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
